### ISSUE TITLE
Areas not being assigned to a region

### ISSUE THREAD

**Issue by Seeloewe** [toilercleaner666/nirn#46]
western_niben_shore_area_area
southern_niben_valley
falkreth_area
yorgim_area
hyaal_bog_area
nabia_lowlands_area_area
sheogorad_area
morsis_area
kizhang_area
sea_serpent_cove_area
gavaudon_area
wayrest_area
menevia_area
hirusa_area
AKAVIR (yep, that's an area)

and all of the Monkey Islands:
rezzayn_area
encrayn_area
tronshin_area
sainan_area
grenidir_area
ronthornsis_area
tainrhun_area
rozzidor_area
krendayn_area
anzian_area
danzidor_area
alladrad_area (one province is super far away from the rest)
enzarysh_area
shrietan_area
lorinmen_area
ruguo_area
ronkolis_area
kalsinkad_area
rasinchad_area
aecrin_area
rankrain_area
berendan_area
aizrain_area
elisinaren_area
rolsindon_area
asradis_area
raindan_area
maizile_area
ilaris
jazinreed_area
haldrazin_area
garnihof_area
zorninda_area
wankani_area
idrion_area
ellezern_area
fesrisch_area
drisech_area
fensaris_area
ahrisan_area
berendan_area

mahraag_sea_area
xarkis_sea_area
yoldoth_sea_area
lebasi_sea_area
wendend_sea_area
andalan_sea_area
zoldakk_sea_area
jaladan_sea_area
halkasis_sea_area
alkadis_sea_area
gindranden_sea_area
dandar_sea_area
yolvon_sea_area
eldain_sea_area
quolaad_sea_area
maldibor_sea_area
taltar_sea_area

**Comment by Anurag-Shah** [comment]
Fixed all the non-monkey isle ones. I'm not sure who did the areas for the monkey isles, they will have to make the region files and the superregion files.

Once this is fixed, please close the issue

**Comment by Anurag-Shah** [comment]
nvm the problem was a typo, "area = {}" instead of "areas = {}" in a bunch of places. closed
